<a href="https://colab.research.google.com/github/jamogh/MLclass/blob/main/Amogh_Jain_RA2111027010010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Machine Learning - 1  </h1>
<br>
<h2>Assignment - 1</h2>
<br>
<h2> Amogh Jain RA2111027010010 - AA1 </h2>

#Importing Libraries

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

from IPython.display import Image

#Imoprting Dataset

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/assignment 1/weather.csv")
print(df)

     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
..       ...      ...       ...          ...       ...         ...   
361      9.0     30.7       0.0          7.6      12.1         NNW   
362      7.1     28.4       0.0         11.6      12.7           N   
363     12.5     19.9       0.0          8.4       5.3         ESE   
364     12.5     26.9       0.0          5.0       7.1          NW   
365     12.3     30.2       0.0          6.0      12.6          NW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29   
1      

In [6]:
df.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0      8.0     24.3       0.0          3.4       6.3          NW   
1     14.0     26.9       3.6          4.4       9.7         ENE   
2     13.7     23.4       3.6          5.8       3.3          NW   
3     13.3     15.5      39.8          7.2       9.1          NW   
4      7.6     16.1       2.8          5.6      10.6         SSE   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0           30.0         SW         NW           6.0  ...           29   
1           39.0          E          W           4.0  ...           36   
2           85.0          N        NNE           6.0  ...           69   
3           54.0        WNW          W          30.0  ...           56   
4           50.0        SSE        ESE          20.0  ...           49   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No   
1       1012.4       1008.4         5         3     17.5     25.7        Yes   
2       1009.5       1007.2         8         7     15.4     20.2        Yes   
3       1005.5       1007.0         2         7     13.5     14.1        Yes   
4       1018.3       1018.5         7         7     11.1     15.4        Yes   

   RISK_MM RainTomorrow  
0      3.6          Yes  
1      3.6          Yes  
2     39.8          Yes  
3      2.8          Yes  
4      0.0           No  

[5 rows x 22 columns]

#Checking Null Values

In [7]:
df.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

#Drop the null rows and columns

In [9]:
df = df.dropna()

In [10]:
df.describe()

MinTemp     MaxTemp    Rainfall  Evaporation    Sunshine  \
count  328.000000  328.000000  328.000000   328.000000  328.000000   
mean     7.742988   20.897561    1.440854     4.702439    8.014939   
std      5.945199    6.707310    4.289427     2.681183    3.506646   
min     -5.300000    7.600000    0.000000     0.200000    0.000000   
25%      2.850000   15.500000    0.000000     2.550000    6.000000   
50%      7.900000   20.400000    0.000000     4.400000    8.750000   
75%     12.800000   25.800000    0.200000     6.600000   10.700000   
max     20.900000   35.800000   39.800000    13.800000   13.600000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count     328.000000    328.000000    328.000000   328.000000   328.000000   
mean       40.396341     10.414634     18.185976    71.100610    44.003049   
std        13.132176      7.811544      8.926759    12.983367    16.605975   
min        13.000000      2.000000      4.000000    36.000000    13.000000   
25%        31.000000      6.000000     11.000000    63.000000    32.000000   
50%        39.000000      7.000000     17.000000    71.000000    42.500000   
75%        46.000000     13.000000     24.000000    80.000000    54.000000   
max        98.000000     41.000000     52.000000    99.000000    93.000000   

       Pressure9am  Pressure3pm    Cloud9am    Cloud3pm     Temp9am  \
count   328.000000   328.000000  328.000000  328.000000  328.000000   
mean   1019.350000  1016.530793    3.905488    4.000000   12.815549   
std       6.715244     6.469774    2.974957    2.652101    5.542521   
min     996.500000   996.800000    0.000000    0.000000    0.100000   
25%    1014.800000  1012.400000    1.000000    1.000000    8.175000   
50%    1019.750000  1016.900000    4.000000    4.000000   13.500000   
75%    1024.300000  1021.125000    7.000000    7.000000   17.200000   
max    1035.700000  1033.200000    8.000000    8.000000   24.700000   

          Temp3pm     RISK_MM  
count  328.000000  328.000000  
mean    19.556402    1.422561  
std      6.644311    4.234023  
min      5.100000    0.000000  
25%     14.500000    0.000000  
50%     18.850000    0.000000  
75%     24.225000    0.200000  
max     34.500000   39.800000

In [11]:
df.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [13]:
df.shape

(328, 22)

#Dividing Data

In [15]:
X = df.drop(columns = 'RainTomorrow', axis = 1)
y = df['RainTomorrow']

#Apply label encoder for all the string attributes

In [16]:
df['WindGustDir'].unique()

array(['NW', 'ENE', 'SSE', 'SE', 'E', 'S', 'N', 'WNW', 'ESE', 'NE', 'NNE',
       'NNW', 'SW', 'W', 'WSW', 'SSW'], dtype=object)

In [17]:
df['WindDir9am'].unique()

array(['SW', 'E', 'N', 'WNW', 'SSE', 'SE', 'S', 'WSW', 'NNE', 'NNW',
       'ENE', 'SSW', 'NW', 'ESE', 'NE', 'W'], dtype=object)

In [19]:
df['WindDir3pm'].unique()

array(['NW', 'W', 'NNE', 'ESE', 'E', 'ENE', 'WSW', 'NE', 'NNW', 'SE', 'S',
       'SW', 'WNW', 'N', 'SSW', 'SSE'], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [38]:
X[X.select_dtypes(include= ['object']).columns] = X[X.select_dtypes(include= ['object']).columns].apply(le.fit_transform)

#“WindGustDir, WindDir”,
#Convert the above attributes into numbers

In [39]:
from sklearn.preprocessing import LabelEncoder

cols = ['MinTemp','MaxTemp','Rainfall','Evaporation','Sunshine','WindGustSpeed','WindSpeed9am','Cloud9am','Cloud3pm']
df[cols] = df[cols].apply(LabelEncoder().fit_transform)
df.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0       90      111         0           15        43          NW   
1      138      130        16           20        75         ENE   
2      135      106        16           27        24          NW   
3      133       42        43           34        69          NW   
4       86       46        13           26        84         SSE   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0              8         SW         NW             2  ...           29   
1             12          E          W             1  ...           36   
2             33          N        NNE             2  ...           69   
3             20        WNW          W            15  ...           56   
4             18        SSE        ESE            10  ...           49   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No   
1       1012.4       1008.4         5         3     17.5     25.7        Yes   
2       1009.5       1007.2         8         7     15.4     20.2        Yes   
3       1005.5       1007.0         2         7     13.5     14.1        Yes   
4       1018.3       1018.5         7         7     11.1     15.4        Yes   

   RISK_MM RainTomorrow  
0      3.6          Yes  
1      3.6          Yes  
2     39.8          Yes  
3      2.8          Yes  
4      0.0           No  

[5 rows x 22 columns]

In [40]:
pd.to_numeric(df.WindGustDir,errors='coerce')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: WindGustDir, Length: 328, dtype: float64

In [41]:
pd.to_numeric(df.WindDir9am,errors='coerce')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: WindDir9am, Length: 328, dtype: float64

In [28]:
pd.to_numeric(df.WindDir3pm,errors='coerce')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: WindDir3pm, Length: 328, dtype: float64

In [29]:
print(df.describe())

          MinTemp     MaxTemp    Rainfall  Evaporation    Sunshine  \
count  328.000000  328.000000  328.000000   328.000000  328.000000   
mean    87.118902   83.326220    4.274390    21.375000   61.390244   
std     47.072472   47.709432    9.629419    13.025132   29.235731   
min      0.000000    0.000000    0.000000     0.000000    0.000000   
25%     45.750000   42.000000    0.000000    10.750000   40.000000   
50%     89.000000   82.000000    0.000000    20.000000   65.500000   
75%    128.000000  121.000000    1.000000    31.000000   85.000000   
max    169.000000  174.000000   43.000000    54.000000  111.000000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count     328.000000    328.000000    328.000000   328.000000   328.000000   
mean       13.085366      4.588415     18.185976    71.100610    44.003049   
std         6.193024      4.234501      8.926759    12.983367    16.605975   
min         0.000000      0.000000      4.000000    36.00

In [42]:
y = le.fit_transform(y)
y

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

#Apply MinMax Scaler

In [43]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
scaled_data = minmax.fit_transform(X)
scaled_data

array([[0.50763359, 0.59219858, 0.        , ..., 0.6292517 , 0.        ,
        0.09045226],
       [0.73664122, 0.68439716, 0.09045226, ..., 0.70068027, 1.        ,
        0.09045226],
       [0.72519084, 0.56028369, 0.09045226, ..., 0.51360544, 1.        ,
        1.        ],
       ...,
       [0.67938931, 0.43617021, 0.        , ..., 0.44897959, 0.        ,
        0.        ],
       [0.67938931, 0.68439716, 0.        , ..., 0.70748299, 0.        ,
        0.        ],
       [0.67175573, 0.80141844, 0.        , ..., 0.79931973, 0.        ,
        0.        ]])

#Construct Linear Regression Model

In [44]:
model1 = LinearRegression()

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [46]:
model1.fit(X_train, y_train)

LinearRegression()

In [47]:
y_predict = model1.predict(X_test)

In [49]:
mse = mean_squared_error(y_predict, y_test)
print(mse)

0.052018262848166394


#Finding R2

In [50]:
r2_initial = r2_score(y_test, y_predict)
print("r2 value is : ", r2_initial)

r2 value is :  0.5116561358478171


# Applying 6 Fold Cross Validation

In [57]:
cv = KFold(n_splits=6, shuffle=True, random_state=3)

In [59]:
cv_score = cross_val_score(model1, X, y, cv = cv, scoring='r2')

#R2 score

In [60]:
cv_score

array([0.5685007 , 0.48208465, 0.56450683, 0.50681711, 0.48563371,
       0.26919298])

In [61]:
np.mean(cv_score)

0.47945599511923925